finished e2e test
headissue/presta-docker-compose pull request #1
Opened 2023-04-03 07:43 UTC by diegotrasobares

2023-04-03 07:44 UTC, globalworming commented on rebuild.sh
> +  sudo docker compose down
```suggestion
  docker compose down
```

2023-04-03 07:45 UTC, globalworming commented on rebuild.sh
> + sudo docker compose up -d --build &
```suggestion
 docker compose up -d --build &
```

2023-04-03 12:20 UTC, diegotrasobares commented on playwright/models/Steps.js
> +  fillPersonalInformation = async () => {
```suggestion
  fillPersonalInformation = async (client) => {
```

2023-04-05 08:04 UTC, globalworming commented
does not work for me, see https://github.com/headissue/presta-docker-compose/blob/a31ee03c61116cfa243e5c5396379fc0bf54e9a5/tmp/error.txt

i did 
```
bash rebuild.sh
cd playwright
npm run test-local
```
and it seems like no mail is in mailcatcher

2023-04-05 08:04 UTC, globalworming requested changes

2023-04-05 08:46 UTC, merged